/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthNotesRouteRouteImport } from './routes/_auth/notes/route'
import { Route as AuthNotesIndexRouteImport } from './routes/_auth/notes/index'
import { Route as AuthNotesNoteIdRouteImport } from './routes/_auth/notes/$noteId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNotesRouteRoute = AuthNotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotesIndexRoute = AuthNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthNotesRouteRoute,
} as any)
const AuthNotesNoteIdRoute = AuthNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AuthNotesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof AuthNotesRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/notes/$noteId': typeof AuthNotesNoteIdRoute
  '/notes/': typeof AuthNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/notes/$noteId': typeof AuthNotesNoteIdRoute
  '/notes': typeof AuthNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/notes': typeof AuthNotesRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_auth/notes/$noteId': typeof AuthNotesNoteIdRoute
  '/_auth/notes/': typeof AuthNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes' | '/login/' | '/notes/$noteId' | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/notes/$noteId' | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/notes'
    | '/login/'
    | '/_auth/notes/$noteId'
    | '/_auth/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/notes': {
      id: '/_auth/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthNotesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notes/': {
      id: '/_auth/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthNotesIndexRouteImport
      parentRoute: typeof AuthNotesRouteRoute
    }
    '/_auth/notes/$noteId': {
      id: '/_auth/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthNotesNoteIdRouteImport
      parentRoute: typeof AuthNotesRouteRoute
    }
  }
}

interface AuthNotesRouteRouteChildren {
  AuthNotesNoteIdRoute: typeof AuthNotesNoteIdRoute
  AuthNotesIndexRoute: typeof AuthNotesIndexRoute
}

const AuthNotesRouteRouteChildren: AuthNotesRouteRouteChildren = {
  AuthNotesNoteIdRoute: AuthNotesNoteIdRoute,
  AuthNotesIndexRoute: AuthNotesIndexRoute,
}

const AuthNotesRouteRouteWithChildren = AuthNotesRouteRoute._addFileChildren(
  AuthNotesRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthNotesRouteRoute: typeof AuthNotesRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNotesRouteRoute: AuthNotesRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
